import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import {once} from 'node:events';
import h from './helpers.mjs';import {SHOTS,ACTS,TOTAL,FPS} from './timeline.mjs';import {createFilm} from './film.mjs';
const DIR=path.dirname(fileURLToPath(import.meta.url));const require=createRequire(import.meta.url);const {createCanvas,GlobalFonts}=require('@napi-rs/canvas');
for(const [f,family]of [['NotoSansSC.ttf','Noto Sans SC'],['NotoSansSC-Semibold.ttf','Noto Sans SC Semibold'],['NotoSerifSC.ttf','Noto Serif SC'],['JetBrainsMono.ttf','JetBrains Mono'],['NotoSans-Regular.ttf','Noto Sans'],['NotoSansMath-Regular.ttf','Noto Sans Math']])GlobalFonts.registerFromPath(path.join(DIR,'public/fonts',f),family);
const {W,H}=h;const canvas=createCanvas(h.W,h.H),{drawFrame}=createFilm(canvas,createCanvas);
const args=process.argv.slice(2),get=(k,d)=>{const i=args.indexOf(k);return i<0?d:args[i+1]};const mode=args[0]||'poster';
if(mode==='poster'){const sec=Number(get('--time',10));const dest=get('--out',path.join(DIR,'outputs/海报.png'));fs.mkdirSync(path.dirname(dest),{recursive:true});drawFrame(Math.round(sec*FPS));fs.writeFileSync(dest,canvas.toBuffer('image/png'));console.log(dest)}
else if(mode==='contact'){const times=JSON.parse(get('--times','[10]'));const cols=Number(get('--cols',4)),sw=480,sh=270,thumb=createCanvas(cols*sw,Math.ceil(times.length/cols)*sh),tc=thumb.getContext('2d');for(let i=0;i<times.length;i++){drawFrame(Math.round(times[i]*FPS));tc.drawImage(canvas,(i%cols)*sw,Math.floor(i/cols)*sh,sw,sh);tc.fillStyle='#000a';tc.fillRect(i%cols*sw,Math.floor(i/cols)*sh,90,22);tc.font='14px sans-serif';tc.fillStyle='#fff';tc.fillText(`${Math.floor(times[i]/18)+1} / ${times[i]}s`,i%cols*sw+4,Math.floor(i/cols)*sh+16)}const dest=get('--out',path.join(DIR,'work/contact.png'));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,thumb.toBuffer('image/png'));console.log(dest)}
else if(mode==='render'){
 const start=Number(get('--start',0)),end=Number(get('--end',TOTAL)),dest=get('--out',path.join(DIR,'outputs/随机之美_无声画面.mp4')),crf=get('--crf','18');fs.mkdirSync(path.dirname(dest),{recursive:true});
 const codec=get('--codec','libx264');const encode=codec==='h264_videotoolbox'?['-c:v',codec,'-b:v','16M','-profile:v','high']:['-c:v','libx264','-preset','fast','-crf',crf,'-threads','3'];
 const ff=spawn('ffmpeg',['-hide_banner','-loglevel','error','-y','-f','rawvideo','-pixel_format','rgba','-video_size',`${W}x${H}`,'-framerate',String(FPS),'-i','pipe:0',...encode,'-pix_fmt','yuv420p','-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709','-movflags','+faststart',dest],{stdio:['pipe','ignore','pipe']});let err='';ff.stderr.on('data',d=>err+=d);ff.stdin.on('error',()=>{});const startAt=Date.now();let last=Date.now();
 for(let f=Math.round(start*FPS);f<Math.round(end*FPS);f++){drawFrame(f);if(!ff.stdin.write(canvas.data()))await once(ff.stdin,'drain');if(Date.now()-last>10000){console.log(JSON.stringify({rendered:((f-start*FPS)/FPS).toFixed(1),total:end-start,fps:Math.round((f-start*FPS)/((Date.now()-startAt)/1000)),file:path.basename(dest)}));last=Date.now()}}
 ff.stdin.end();const [code]=await once(ff,'close');if(code!==0)throw Error(err);console.log(JSON.stringify({done:dest,seconds:(Date.now()-startAt)/1000}));
}
export {drawFrame,canvas};
